#!/bin/bash
if [ ! "$BASH" ]
then
echo "Este script foi feito para funcionar com as novas payloads da claro
Reiniciando o Script usando BASH em 3 segundos..."
sleep 3
bash $0 $@
exit $?
fi
clear
menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"


echo -e "$menu
                        SQUID3                  $fim"

echo -e "$cyanClaro
Este é um script que configura uma nova versão do SQUID3 para sistemas Debian-Based.
Script criado por Matheus Larcher.
$fim"
echo -e "$cyanClaro
Instalando SQUID3...$fim"
apt-get update 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get install squid3 -y 1>/dev/null 2>/dev/null
apt-get install ssh -y 1>/dev/null 2>/dev/null

echo -e "$azulClaro
Configurando SQUID3...$fim"

cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//' > /etc/so 
apt-get install curl -y
IP=$(curl https://api.ipify.org/) 
clear
echo " [ Configurando seu VPS ] "
 sleep 3
clear
echo " "
echo " Seu endereço de
IP [ $IP ] "
echo " "
clear

rm /bin/IPVPS
echo "$IP" > /bin/IPVPS
rm /etc/squid3/squid.conf
echo "# Portas do SQUID
http_port 80
http_port 8080
http_port 3128

# ACLs e Liberações
acl vps1 dstdomain -i 127.0.0.1
acl vps2 dstdomain -i localhost
acl vps3 dstdomain -i $IP
acl vps4 dstdomain -i .br
acl vps5 dstdomain -i .com
acl vps6 dstdomain -i .net
acl CONNECT method CONNECT
acl GET method GET
acl POST method POST
acl OPTIONS method OPTIONS
acl DELETE method DELETE
acl HEAD method HEAD
http_access allow vps1
http_access allow vps2
http_access allow vps3
http_access allow vps4
http_access allow vps5
http_access allow vps6
#cache deny all
http_access deny all

# Anonimo
forwarded_for off
via off

# Pipeline
#pipeline_prefetch on
" > /etc/squid3/squid.conf

echo -e "$azulClaro
Configurando SSH...$fim"

rm /etc/ssh/sshd_config
echo "Port 22
Port 443
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
PermitTunnel yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config

echo -e "
.bookclaro.com.br
.claro.com.ar
.claro.com.br
.claro.com.co
.claro.com.ec
.claro.com.gt
.claro.com.ni
.claro.com.pe
.claro.com.sv
.claro.cr
.clarocurtas.com.br
.claroideas.com
.claroideias.com.br
.claromusica.com
.clarosomdechamada.com.br
.clarovideo.com
.facebook.net
.netclaro.com.br
.oi.com.br
.oimusica.com.br
.speedtest.net
.tim.com.br
.timanamaria.com.br
www.timbeta.com.br
www.developers.deezer.com.br
www.timmusicstore.com.br
.vivo.com.br
.d1n212ccp6ldpw.cloudfront.net
.rdio.com
.ec2-52-22-60-103.compute-1.amazonaws.com
.portalrecarga.vivo.com.br/recarga/home/
.w1716.smartadserver.com
interatividade.vivo.ddivulga.com/produto
navegue.vivo.ddivulga.com/pacote
.m.clarosomdechamada.com.br
m.clarosomdechamada.com.br
m.claroseguridad.com
.clarosomdechamada.com.br
.portalsva2.vivo.com.br" > /etc/payloads

echo -e "$cyanClaro
Recarregando serviços...$fim"
squid3 -k reconfigure 1>/dev/null 2>/dev/null
service ssh restart 1>/dev/null 2>/dev/null
service squid3 restart 1>/dev/null 2>/dev/null

# echo -e "$verde
# Correção de problemas de pacotes no SSH...$fim"
# apt-get install ethtool -y 1>/dev/null 2>/dev/null
# read -p "Digite o nome da sua interface de rede (Padrão: eth0): " interface
# if [ "$interface" = "" ]
# then
# interface=eth0
# fi
# ethtool -G $interface rx 999999999 tx 999999999 1>/dev/null 2>/dev/null
rm /root/configuracao
echo -e "$verde
Configuração terminada.$fim"
