#!/bin/bash
apt-get update
apt-get install squid* -y 1>/dev/null 2>/dev/null
apt-get upgrade -y
apt-get install squid3 bc screen nano unzip dos2unix wget -y
killall apache2
apt-get purge apache2 -y
if [ -f "/usr/sbin/ufw" ] ; then
ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
fi
echo "Configurando SQUID3..."

cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//' > /etc/so 
apt-get install curl -y
IP=$(curl https://api.ipify.org/) 
clear
echo " [ Configurando seu VPS ] "
 sleep 3
clear
echo " "
echo " Seu endereço de
IP [ $IP ] "
echo " "
clear

rm /etc/IPVPS 2> /dev/null
echo "$IP" > /etc/IPVPS


if [ -d "/etc/squid3/" ]
then
rm /etc/squid3/squid.conf
echo "# Portas do SQUID
http_port 80
http_port 8080
http_port 3128

# ACLs e Liberações
acl vps1 dstdomain -i 127.0.0.1
acl vps2 dstdomain -i localhost
acl vps3 dstdomain -i $IP
acl vps4 dstdomain -i .br
acl vps5 dstdomain -i .com
acl vps6 dstdomain -i .net
acl CONNECT method CONNECT
acl GET method GET
acl POST method POST
acl OPTIONS method OPTIONS
acl DELETE method DELETE
acl HEAD method HEAD
http_access allow vps1
http_access allow vps2
http_access allow vps3
http_access allow vps4
http_access allow vps5
http_access allow vps6
#cache deny all
http_access deny all

# Anonimo
forwarded_for off
via off

# Pipeline
#pipeline_prefetch on
" > /etc/squid3/squid.conf

if [ ! -f "/etc/init.d/squid3" ]
	then
		service squid3 reload > /dev/null
	else
		/etc/init.d/squid3 reload > /dev/null
	fi
	if [ ! -f "/etc/init.d/ssh" ]
	then
		service ssh reload > /dev/null
	else
		/etc/init.d/ssh reload > /dev/null
	fi
fi
if [ -d "/etc/squid/" ]
then
rm /etc/squid/squid.conf
echo "# Portas do SQUID
http_port 80
http_port 8080
http_port 3128

# ACLs e Liberações
acl vps1 dstdomain -i 127.0.0.1
acl vps2 dstdomain -i localhost
acl vps3 dstdomain -i $IP
acl vps4 dstdomain -i .br
acl vps5 dstdomain -i .com
acl vps6 dstdomain -i .net
acl CONNECT method CONNECT
acl GET method GET
acl POST method POST
acl OPTIONS method OPTIONS
acl DELETE method DELETE
acl HEAD method HEAD
http_access allow vps1
http_access allow vps2
http_access allow vps3
http_access allow vps4
http_access allow vps5
http_access allow vps6
#cache deny all
http_access deny all

# Anonimo
forwarded_for off
via off

# Pipeline
#pipeline_prefetch on
" > /etc/squid/squid.conf

echo "Configurando SSH..."
rm /etc/ssh/sshd_config
echo "
Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
PermitTunnel yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes
Compression yes" >> /etc/ssh/sshd_config
if [ ! -f "/etc/init.d/ssh" ]
	then
		service ssh reload > /dev/null
	else
		/etc/init.d/ssh reload > /dev/null
	fi
fi
rm OpenVPN-install*
clear
echo "Configurando OpenVPN"
sleep 3s

wget https://raw.githubusercontent.com/matheuslarcher20/VpsPack-master/master/OpenVPN && bash OpenVPN
mv OpenVPN /bin/OpenVPN
chmod +x /bin/OpenVPN



