#!/bin/bash
clear
echo -e "\033[1;30m---------------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m Usuario          Senha         Data E.        Logins(SSH)  Status(OpenVPN)  \033[0m"
echo -e "\033[1;30m---------------------------------------------------------------------------\033[0m"
for users in `cat /etc/detalhesusers.cache |awk -F : '{print $1}'`
do
#users=$(cat /etc/detalhesusers.cache |awk -F : '{print $1}')
senha=$(cat /etc/detalhesusers.cache |grep -w $users |awk -F : '{print $2}')
data=$(cat /etc/detalhesusers.cache |grep -w $users |awk -F : '{print $3}')
usernum=$(cat /etc/detalhesusers.cache |grep -w $users |awk -F : '{print $4}')
limitecs=$(cat /etc/detalhesusers.cache |grep -w $users |awk -F : '{print $5}')
status1=$(cat /etc/detalhesusers.cache |grep -w $users |awk -F : '{print $6}')

detalhesdata=$(printf '%-14s' "$data")
detalheslimit=$(printf '%-8s' "$limitecs")
detalhes=$(printf ' %-15s' "$users")
detalhespass=$(printf '%-11s' "$senha")

if [[ $status1 = 'Online' ]]; then
status='\033[1;32mOnline'
else
status='\033[1;31mOffline'
fi
if [ $usernum -eq 0 ]; then

echo -e "\033[1;33m$detalhes  $detalhespass  $detalhesdata    \033[1;31m$usernum\033[2;37m \ \033[1;33m$detalheslimit  $status\033[0m"
else
echo -e "\033[1;33m$detalhes  $detalhespass  $detalhesdata    \033[1;32m$usernum\033[2;37m \ \033[1;33m$detalheslimit  $status\033[0m"
fi
echo -e "\033[1;30m---------------------------------------------------------------------------\033[0m"
done
echo -e "\033[1;33mTotal: $usertotal     Online(SSH): \033[1;32m$calculo    \033[1;33mOnline(OpenVPN): \033[1;32m$calculovpn\033[0m
"
