#!/bin/bash
echo -e "\033[44;1;37m        Criar Usuário          \033[0m"
        echo -e "\033[1;32mNome do novo usuario:\033[0;37m"; read -p " " name
        echo -e "\033[1;32mSenha para o usuario $name:\033[0;37m"; read -p " " pass
        echo -e "\033[1;32mQuantos dias usuario $name deve durar:\033[0;37m"; read -p " " daysrnf
        echo -e "\033[1;32mLimite de Conexoes no SSH para $name: \033[0;37m"; read -p " " num
        echo -e "\033[0m"

if (echo $name | egrep '[^a-zA-Z0-9]' &> /dev/null)
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um nome de usuário inválido! \033[0m"
exit
else
echo ""
fi

if (echo $pass | egrep '[^a-zA-Z0-9]' &> /dev/null)
then
echo -e "\033[1;31mErro!!\033[0;31m Você digitou uma senha inválida! \033[0m"
exit
else
echo ""
fi
sizemax=$(echo ${#name})
if [[ $sizemax -gt 12 ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um nome de usuário muito grande,
 Use no máximo 12 caracteres!\033[0m"
exit
else
echo ""
fi
sizemaxpass=$(echo ${#pass})
if [[ $sizemaxpass -gt 9 ]]
then
echo "\033[1;31mErro!! \033[0;31mVocê digitou uma senha muito grande,
 Use no máximo 9 caracteres!\033[0m"
exit
else
echo ""
fi
sizemaxnum=$(echo ${#num})
if [[ $sizemaxnum -gt 2 ]]
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou Limite de Conexoes muito alto,
 É permitido no maximo 99 conexoes!\033[0m"
exit
else
echo ""
fi
if (echo $num | egrep '[^0-9]' &> /dev/null)
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou um número de conexões inválido!\033[0m"
exit
else
echo ""
fi
if (echo $daysrnf | egrep '[^0-9]' &> /dev/null)
then
echo -e "\033[1;31mErro!! \033[0;31mVocê digitou uma data inválida!\033[0m"
exit
else
echo ""
fi
if [[ $daysrnf -gt 35 ]]
then
echo -e "\033[1;31mErro!! \033[0;31mData invalida,
 É permitido no maximo 35 dias!\033[0m"
exit
else
echo ""
fi

       if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
        then
                echo -e "\033[1;31mUsuario $name ja existe\033[0m"
        exit
        else
                valid=$(date '+%C%y/%m/%d' -d " +$daysrnf days")
                datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
echo "$name:$pass:$num:$valid" >> /etc/Usercreate.cache
fi
clear
                echo -e "\033[1;32m################################\033[0m"
                echo -e "\033[1;36m                        \033[0m"
                echo -e "\033[1;36m                        \033[2;40m"
                echo -e "\033[1;36mUsuario: \033[2;37m$name"
                echo -e "\033[1;36mSenha: \033[2;37m$pass"
                echo -e "\033[1;36mExpira: \033[2;37m$datexp"
                echo -e "\033[1;36mConexoes(SSH): \033[2;37m$num"
                echo -e "\033[1;36m                        \033[2;40m"
                echo -e "\033[1;36m                        \033[0m"
                echo -e "\033[1;32m################################\033[0m"
                echo -e "\033[1;36m                        \033[0m"
                echo -e "\033[1;36m                        \033[0m"
echo -e "\033[1;32m Pedido de novo usuario realisado com susesso!!
 Aguarde a aprovação automática!!
\033[0m Caso a aprovação não ocorra em até 2 minutos, entre em contado com um adiministrador."
