#!/bin/bash
read -p "Qual nome do novo usuarios adm? " user
useradd -m -d /clientes/$user $user && cp /bin/criar /clientes/$user && cp /bin/apagar /clientes/$user && cp /bin/pack /clientes/$user

passwd $user
