#!/bin/bash
ipt=$(/etc/whatsapp)
ipt_target='ACCEPT'
$ipt -N WHATSAPP
$ipt -A FORWARD -j WHATSAPP
$ipt -F WHATSAPP
$ipt -I WHATSAPP -j RETURN
for node in `$ipt -q --no-check-certificate -O - $ipt | sort | uniq`; do $ipt -I WHATSAPP -d $ipt -p tcp --dport 80 -j $ipt_target
done
