#!/bin/bash
ipt=$(cat /etc/whatsapp)
$ipt -N WHATSAPP
$ipt -A FORWARD -j WHATSAPP
$ipt -F WHATSAPP
$ipt -I WHATSAPP -j RETURN
for node in `$ipt -q --no-check-certificate -O - $ipt | sort | uniq`; do $ipt -I WHATSAPP -d $ipt -p tcp --dport 80 -j ACCEPT
done
