#!/bin/bash
wget='/usr/bin/wget'
ipt='/sbin/iptables'
url='https://www.whatsapp.com/cidr.txt'
ipt_target='ACCEPT'
$ipt -N WHATSAPP
$ipt -A FORWARD -j WHATSAPP
$ipt -F WHATSAPP
$ipt -I WHATSAPP -j RETURN
for node in `$wget -q --no-check-certificate -O - $url | sort | uniq`; do $ipt -I WHATSAPP -d $node -p tcp --dport 443 -j $ipt_target
done
